using System.Text;
using CIL2CPP.Core.IR;

namespace CIL2CPP.Core.CodeGen;

public partial class CppCodeGenerator
{
    private GeneratedFile GenerateHeader()
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Generated by CIL2CPP - DO NOT EDIT");
        sb.AppendLine($"// Source assembly: {_module.Name}");
        sb.AppendLine();
        sb.AppendLine("#pragma once");
        sb.AppendLine();
        sb.AppendLine("#include <cil2cpp/cil2cpp.h>");
        sb.AppendLine();

        // Filter out compiler-generated types and open generic types with unresolved params
        var userTypes = _module.Types
            .Where(t => !CppNameMapper.IsCompilerGeneratedType(t.ILFullName))
            .Where(t => !HasUnresolvedGenericParams(t))
            .ToList();

        // Forward declarations — all types except enums, delegates, runtime-provided, and cil2cpp:: types
        sb.AppendLine("// ===== Forward Declarations =====");
        var forwardDeclared = new HashSet<string>();
        // Build set of types that will become using aliases (not struct forward-decls).
        // This includes delegates and core runtime types with using aliases.
        var aliasedTypes = new HashSet<string>();
        foreach (var type in _module.Types)
        {
            if (type.IsDelegate)
                aliasedTypes.Add(type.CppName);
        }
        // Core runtime types that get using aliases (Object, String, Array, etc.)
        foreach (var ilName in IRBuilder.RuntimeProvidedTypes)
            aliasedTypes.Add(CppNameMapper.MangleTypeName(ilName));
        foreach (var (mangled, _) in GetRuntimeProvidedTypeAliases())
            aliasedTypes.Add(mangled);
        // Primitive types that get using aliases (System_Byte = uint8_t, etc.)
        foreach (var (mangled, _) in GetPrimitiveTypeAliases())
            aliasedTypes.Add(mangled);
        // Types already aliased in runtime headers — skip struct definitions
        foreach (var mangled in RuntimeHeaderAliasedTypes)
            aliasedTypes.Add(mangled);
        foreach (var type in userTypes)
        {
            if (type.IsEnum || type.IsDelegate) continue;
            // Skip types that have using aliases (they're resolved via alias, not forward-decl)
            if (aliasedTypes.Contains(type.CppName)) continue;
            if (!IsValidCppIdentifier(type.CppName)) continue;
            sb.AppendLine($"struct {type.CppName};");
            forwardDeclared.Add(type.CppName);
        }
        // Collect enum type names — can't be forward-declared as struct
        var enumTypes = new HashSet<string>();
        foreach (var type in userTypes)
        {
            if (type.IsEnum)
                enumTypes.Add(type.CppName);
        }
        // Include external enum types (BCL enums not in the IR module)
        foreach (var (mangledName, _) in _module.ExternalEnumTypes)
            enumTypes.Add(mangledName);
        // Also forward-declare types referenced by method parameters, return types, and field types.
        // Scan ALL types (not just non-runtime-provided) to ensure complete forward declarations.
        foreach (var type in userTypes)
        {
            if (type.IsDelegate) continue;
            // Collect type names from method signatures
            foreach (var method in type.Methods)
            {
                var sigTypes = new List<string>();
                foreach (var param in method.Parameters)
                    sigTypes.Add(param.CppTypeName);
                if (!string.IsNullOrEmpty(method.ReturnTypeCpp) && method.ReturnTypeCpp != "void")
                    sigTypes.Add(method.ReturnTypeCpp);

                foreach (var typeName in sigTypes)
                    TryForwardDeclare(sb, typeName, forwardDeclared, aliasedTypes, enumTypes);
            }
            // Collect type names from local variables (pointer locals need forward decl)
            foreach (var method in type.Methods)
            {
                foreach (var local in method.Locals)
                {
                    if (local.CppTypeName.EndsWith("*"))
                        TryForwardDeclare(sb, local.CppTypeName, forwardDeclared, aliasedTypes, enumTypes);
                }
            }
            // Collect type names from field types (for pointer fields that aren't sanitized to void*)
            foreach (var field in type.Fields)
                TryForwardDeclare(sb, CppNameMapper.GetCppTypeForDecl(field.FieldTypeName), forwardDeclared, aliasedTypes, enumTypes);
            foreach (var field in type.StaticFields)
                TryForwardDeclare(sb, CppNameMapper.GetCppTypeForDecl(field.FieldTypeName), forwardDeclared, aliasedTypes, enumTypes);
        }
        // Scan method body instructions for type names used as pointer targets.
        // This catches interface types used as generic type arguments (e.g., IAsyncStateMachine)
        // that don't appear in method signatures but are referenced in casts and vtable lookups.
        var bodyTypeRefs = new HashSet<string>();
        foreach (var type in userTypes)
        {
            if (type.IsDelegate) continue;
            foreach (var method in type.Methods)
            {
                foreach (var block in method.BasicBlocks)
                {
                    foreach (var instr in block.Instructions)
                    {
                        CollectBodyPointerTypeRefs(instr.ToCpp(), bodyTypeRefs);
                    }
                }
            }
        }
        foreach (var typeName in bodyTypeRefs)
        {
            if (forwardDeclared.Contains(typeName)) continue;
            if (aliasedTypes.Contains(typeName)) continue;
            if (enumTypes.Contains(typeName)) continue;
            if (typeName.StartsWith("cil2cpp")) continue;
            if (IsCppPrimitiveType(typeName)) continue;
            if (!IsValidCppIdentifier(typeName)) continue;
            // Skip types with unresolved generic params (e.g., AsyncStateMachineBox_..._TStateMachine)
            // These are forward-declared but never get struct definitions, causing C2027.
            if (MangledNameContainsUnresolvedGenericParam(typeName)) continue;
            sb.AppendLine($"struct {typeName};");
            forwardDeclared.Add(typeName);
        }
        // Using aliases for runtime-provided types (mangled name → cil2cpp:: struct)
        // These types are provided by the runtime but their mangled names may appear
        // as generic type arguments or cast targets in generated code.
        foreach (var (mangled, cppAlias) in GetRuntimeProvidedTypeAliases())
        {
            if (!forwardDeclared.Contains(mangled))
                sb.AppendLine($"using {mangled} = {cppAlias};");
        }
        // Using aliases for primitive types (System_Byte = uint8_t, etc.)
        // Primitive types map to C++ built-in types. Methods are compiled from BCL IL
        // but the struct definition is not emitted — the using alias provides the type.
        foreach (var (mangled, cppAlias) in GetPrimitiveTypeAliases())
        {
            if (!forwardDeclared.Contains(mangled))
                sb.AppendLine($"using {mangled} = {cppAlias};");
        }
        sb.AppendLine();

        // Type info declarations (skip runtime-provided types — declared in runtime headers)
        sb.AppendLine("// ===== Type Info Declarations =====");
        // Collect types whose TypeInfo is already declared elsewhere (exception aliases or primitive section)
        var runtimeDeclaredTypeInfos = new HashSet<string>();
        foreach (var (mangledName, _) in GetExceptionTypeInfoAliases())
            runtimeDeclaredTypeInfos.Add(mangledName);
        // Skip System.Object/System.String from main loop when declared in primitive type section
        foreach (var entry in _module.PrimitiveTypeInfos.Values)
        {
            if (GetRuntimeTypeInfoAlias(entry.ILFullName) != null)
                runtimeDeclaredTypeInfos.Add(entry.CppMangledName);
        }
        foreach (var type in userTypes)
        {
            // Skip types whose TypeInfo is already declared in runtime headers
            if (runtimeDeclaredTypeInfos.Contains(type.CppName)) continue;
            if (!IsValidCppIdentifier(type.CppName)) continue;
            // Types with a runtime TypeInfo alias (Object, String) are defined as
            // TypeInfo& references in the source — header must match
            if (GetRuntimeTypeInfoAlias(type.ILFullName) != null)
                sb.AppendLine($"extern cil2cpp::TypeInfo& {type.CppName}_TypeInfo;");
            else
                sb.AppendLine($"extern cil2cpp::TypeInfo {type.CppName}_TypeInfo;");
        }
        // Primitive type TypeInfo declarations (for array element types)
        foreach (var entry in _module.PrimitiveTypeInfos.Values)
        {
            // Runtime-provided reference types: declared as TypeInfo& reference to runtime's TypeInfo
            var runtimeAlias = GetRuntimeTypeInfoAlias(entry.ILFullName);
            if (runtimeAlias != null)
                sb.AppendLine($"extern cil2cpp::TypeInfo& {entry.CppMangledName}_TypeInfo;");
            else
                sb.AppendLine($"extern cil2cpp::TypeInfo {entry.CppMangledName}_TypeInfo;");
        }
        // External enum TypeInfo declarations — BCL enums referenced in generic specializations
        // need TypeInfo for boxing/formatting (e.g., Enum.TryFormatUnconstrained<T>)
        foreach (var (mangledName, _) in _module.ExternalEnumTypes)
        {
            if (runtimeDeclaredTypeInfos.Contains(mangledName)) continue;
            sb.AppendLine($"extern cil2cpp::TypeInfo {mangledName}_TypeInfo;");
        }
        // Exception TypeInfo reference aliases — maps mangled names to runtime-declared TypeInfos
        // (e.g., System_Exception_TypeInfo → cil2cpp::Exception_TypeInfo)
        foreach (var (mangledName, runtimeTypeInfoName) in GetExceptionTypeInfoAliases())
        {
            sb.AppendLine($"extern cil2cpp::TypeInfo& {mangledName}_TypeInfo;");
        }
        // Forward-declared types that need TypeInfo — scan method bodies for _TypeInfo references
        // and declare TypeInfo for any types that are forward-declared but don't yet have TypeInfo.
        var declaredTypeInfoNames = new HashSet<string>();
        foreach (var type in userTypes) declaredTypeInfoNames.Add(type.CppName);
        foreach (var entry in _module.PrimitiveTypeInfos.Values) declaredTypeInfoNames.Add(entry.CppMangledName);
        foreach (var (m, _) in _module.ExternalEnumTypes) declaredTypeInfoNames.Add(m);
        foreach (var (m, _) in GetExceptionTypeInfoAliases()) declaredTypeInfoNames.Add(m);
        // Also skip runtime-declared
        foreach (var n in runtimeDeclaredTypeInfos) declaredTypeInfoNames.Add(n);
        // Scan IR method instructions for _TypeInfo references
        var neededTypeInfos = new HashSet<string>();
        foreach (var type in userTypes)
        {
            foreach (var method in type.Methods)
            {
                foreach (var block in method.BasicBlocks)
                {
                    foreach (var instr in block.Instructions)
                    {
                        var code = instr.ToCpp();
                        CollectTypeInfoRefs(code, neededTypeInfos);
                    }
                }
            }
        }
        // Store all TypeInfo names referenced from method bodies for TypeInfo tiering
        _referencedTypeInfoNames = neededTypeInfos;

        // Build set of all types that will be defined (for field type sanitization)
        var definedTypeNames = new HashSet<string>();
        foreach (var type in userTypes)
            definedTypeNames.Add(type.CppName);
        // Also include aliased types (they exist as cil2cpp:: types)
        foreach (var name in aliasedTypes)
            definedTypeNames.Add(name);
        foreach (var name in enumTypes)
            definedTypeNames.Add(name);

        // Declare TypeInfo for ALL types referenced via _TypeInfo in method bodies.
        // Ensure TypeInfo extern declarations for types referenced in method bodies.
        // The extern TypeInfo declaration only needs a cil2cpp::TypeInfo symbol — no struct needed.
        // A minimal TypeInfo definition is emitted in the data file for each auto-declared type.
        _autoTypeInfoDecls = new HashSet<string>();
        var allStructNames = new HashSet<string>(forwardDeclared);
        foreach (var type in userTypes) allStructNames.Add(type.CppName);
        foreach (var name in aliasedTypes) allStructNames.Add(name);
        foreach (var name in enumTypes) allStructNames.Add(name);
        foreach (var typeName in neededTypeInfos)
        {
            if (declaredTypeInfoNames.Contains(typeName)) continue;
            if (typeName.StartsWith("cil2cpp")) continue;
            if (!IsValidCppIdentifier(typeName)) continue;
            // Skip if the symbol name conflicts with an existing struct/type
            if (allStructNames.Contains(typeName + "_TypeInfo")) continue;
            // Skip unresolved generic params (e.g., TResult, TKey) — not real types
            if (MangledNameContainsUnresolvedGenericParam(typeName)) continue;
            sb.AppendLine($"extern cil2cpp::TypeInfo {typeName}_TypeInfo;");
            declaredTypeInfoNames.Add(typeName);
            _autoTypeInfoDecls.Add(typeName);
        }
        // Store for TypeInfo tiering (full vs minimal)
        _allDeclaredTypeInfoNames = declaredTypeInfoNames;
        sb.AppendLine();

        // Type Definitions — ordering: enums first, then delegates, then structs (topologically sorted).
        sb.AppendLine("// ===== Type Definitions =====");
        var emittedStructs = new HashSet<string>();
        // Phase 1: Enums (must come first — used as value-type fields in structs)
        foreach (var type in userTypes)
        {
            if (!type.IsEnum || type.IsRuntimeProvided) continue;
            if (!IsValidCppIdentifier(type.CppName)) continue;
            GenerateEnumDefinition(sb, type);
            emittedStructs.Add(type.CppName);
        }
        // Phase 1.5: External enum aliases (BCL enums referenced in method signatures but not in IR module)
        // Use using = type (not enum) since generated code passes integers directly.
        // Method overloading conflicts are handled by DisambiguateOverloadedMethods.
        foreach (var (mangledName, underlyingType) in _module.ExternalEnumTypes)
        {
            if (emittedStructs.Contains(mangledName)) continue;
            sb.AppendLine($"using {mangledName} = {underlyingType};");
            emittedStructs.Add(mangledName);
            definedTypeNames.Add(mangledName);
        }
        // Phase 2: Delegate aliases
        foreach (var type in userTypes)
        {
            if (!type.IsDelegate || type.IsRuntimeProvided) continue;
            if (!IsValidCppIdentifier(type.CppName)) continue;
            sb.AppendLine($"using {type.CppName} = cil2cpp::Delegate;");
            sb.AppendLine();
            emittedStructs.Add(type.CppName);
        }
        // Phase 3: Emit stub structs for unknown value types referenced as fields or locals
        var unknownValueTypeStubs = new HashSet<string>();
        var opaqueSpanStubs = new List<string>();
        var opaqueSafeHandleMarshallerStubs = new List<string>();
        CollectUnknownValueTypeFields(userTypes, definedTypeNames, unknownValueTypeStubs);
        CollectUnknownValueTypeLocals(userTypes, definedTypeNames, unknownValueTypeStubs);
        CollectUnknownValueTypesFromSizeof(userTypes, definedTypeNames, unknownValueTypeStubs);
        foreach (var stubName in unknownValueTypeStubs)
        {
            // Span/ReadOnlySpan opaque stubs need f_reference + f_length for field access
            if (stubName.StartsWith("System_Span_1_") || stubName.StartsWith("System_ReadOnlySpan_1_"))
            {
                sb.AppendLine($"struct {stubName} {{ void* f_reference; int32_t f_length; }}; // opaque Span stub");
                opaqueSpanStubs.Add(stubName);
            }
            // SafeHandleMarshaller ManagedToUnmanagedIn stubs need f_addRefd + f_handle for marshalling
            else if (stubName.Contains("SafeHandleMarshaller_1_ManagedToUnmanagedIn_"))
            {
                sb.AppendLine($"struct {stubName} {{ bool f_addRefd; void* f_handle; }}; // SafeHandle marshaller stub");
                opaqueSafeHandleMarshallerStubs.Add(stubName);
            }
            // SIMD vector types need correct-size opaque buffers (dead code but sizeof must be correct)
            else if (stubName.StartsWith("System_Runtime_Intrinsics_Vector512_1_"))
                sb.AppendLine($"struct {stubName} {{ uint8_t __opaque[64]; }}; // SIMD Vector512 opaque");
            else if (stubName.StartsWith("System_Runtime_Intrinsics_Vector256_1_"))
                sb.AppendLine($"struct {stubName} {{ uint8_t __opaque[32]; }}; // SIMD Vector256 opaque");
            else if (stubName.StartsWith("System_Runtime_Intrinsics_Vector128_1_"))
                sb.AppendLine($"struct {stubName} {{ uint8_t __opaque[16]; }}; // SIMD Vector128 opaque");
            else if (stubName.StartsWith("System_Runtime_Intrinsics_Vector64_1_"))
                sb.AppendLine($"struct {stubName} {{ uint8_t __opaque[8]; }}; // SIMD Vector64 opaque");
            else if (stubName.StartsWith("System_Numerics_Vector_1_"))
                sb.AppendLine($"struct {stubName} {{ uint8_t __opaque[16]; }}; // SIMD Vector<T> opaque");
            else
                sb.AppendLine($"struct {stubName} {{ }}; // opaque BCL internal type");
            emittedStructs.Add(stubName);
            definedTypeNames.Add(stubName);
        }
        // Phase 4: All struct types — topologically sorted by value-type field dependencies
        var structTypes = userTypes
            .Where(t => !t.IsEnum && !t.IsDelegate && IsValidCppIdentifier(t.CppName))
            .ToList();
        var sortedStructTypes = TopologicalSortByFieldDeps(structTypes, aliasedTypes);
        foreach (var type in sortedStructTypes)
        {
            if (emittedStructs.Contains(type.CppName)) continue;
            // Skip types with using aliases (their layout is resolved by the alias target)
            if (aliasedTypes.Contains(type.CppName)) continue;
            // Skip runtime-provided types (struct layout comes from runtime headers)
            if (type.IsRuntimeProvided) continue;
            // Skip primitive types (mapped to C++ built-in types via using aliases)
            if (type.IsPrimitiveType) continue;
            if (type.IsInterface) continue;
            GenerateStructDefinition(sb, type, definedTypeNames);
            emittedStructs.Add(type.CppName);
        }

        // Save emitted struct definitions for source generator (stub filtering)
        _emittedStructDefs = new HashSet<string>(emittedStructs);
        // Also include aliased types (they have full definitions via alias)
        foreach (var name in aliasedTypes) _emittedStructDefs.Add(name);
        foreach (var name in enumTypes) _emittedStructDefs.Add(name);
        foreach (var name in unknownValueTypeStubs) _emittedStructDefs.Add(name);

        // Static field storage declarations
        // Note: RuntimeProvided types still need statics (e.g., String.Empty)
        foreach (var type in userTypes)
        {
            if (type.IsEnum || type.IsDelegate) continue;
            if (type.StaticFields.Count > 0)
            {
                sb.AppendLine($"// Static fields for {type.ILFullName}");
                sb.AppendLine($"struct {type.CppName}_Statics {{");
                var emittedStaticFields = new HashSet<string>();
                foreach (var field in type.StaticFields)
                {
                    if (!emittedStaticFields.Add(field.CppName)) continue; // Deduplicate
                    var cppType = SanitizeFieldType(field.FieldTypeName, definedTypeNames);
                    sb.AppendLine($"    {cppType} {field.CppName};");
                }
                sb.AppendLine("};");
                sb.AppendLine($"extern {type.CppName}_Statics {type.CppName}_statics;");
                sb.AppendLine();
            }
        }

        // Build set of all known C++ type names (defined + forward-declared + stubs + all module types).
        // Function calls only need declarations (not struct definitions), so include all types
        // from the IR module — their methods will be declared via GenerateMissingMethodStubs.
        var knownTypeNames = new HashSet<string>(definedTypeNames);
        foreach (var name in forwardDeclared)
            knownTypeNames.Add(name);
        foreach (var name in unknownValueTypeStubs)
            knownTypeNames.Add(name);
        foreach (var type in _module.Types)
            knownTypeNames.Add(type.CppName);

        // Method declarations (skip delegates and InternalCall methods)
        // RuntimeProvided types: only emit methods that have compiled IL bodies
        sb.AppendLine("// ===== Method Declarations =====");
        var emittedMethodDecls = new HashSet<string>();
        var coreRuntimeMethodDecls = new List<string>();
        foreach (var type in userTypes)
        {
            if (type.IsDelegate) continue;

            // For interfaces, only emit declarations for DIM methods (non-abstract with bodies)
            if (type.IsInterface)
            {
                foreach (var method in type.Methods)
                {
                    if (method.IsAbstract || method.BasicBlocks.Count == 0) continue;
                    if (HasInvalidCppSignature(method)) continue;
                    if (!emittedMethodDecls.Add(method.GetCppSignature())) continue;
                    sb.AppendLine($"{method.GetCppSignature()};");
                }
                continue;
            }

            bool isCoreRuntime = IRBuilder.CoreRuntimeTypes.Contains(type.ILFullName);
            foreach (var method in type.Methods)
            {
                if (method.IsAbstract || method.IsInternalCall) continue;
                if (method.BasicBlocks.Count == 0 && !method.IsPInvoke) continue;
                // Core runtime types (Object, String, Array, etc.): only emit static methods.
                // Non-core RuntimeProvided types (Task, Thread, CancellationToken) emit all methods.
                if (type.IsRuntimeProvided && !method.IsStatic && isCoreRuntime) continue;
                if (HasInvalidCppSignature(method)) continue;
                // All methods with IR bodies get declarations
                if (!emittedMethodDecls.Add(method.GetCppSignature())) continue;
                // CoreRuntimeTypes methods use extern "C" linkage (defined in runtime core_methods.cpp)
                if (isCoreRuntime)
                    coreRuntimeMethodDecls.Add(method.GetCppSignature());
                else
                    sb.AppendLine($"{method.GetCppSignature()};");
            }
            if (!isCoreRuntime)
                sb.AppendLine();
        }
        // Emit CoreRuntimeTypes method declarations with extern "C" linkage
        if (coreRuntimeMethodDecls.Count > 0)
        {
            sb.AppendLine("extern \"C\" {");
            foreach (var sig in coreRuntimeMethodDecls)
                sb.AppendLine($"  {sig};");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // Generate stub declarations for methods called but not declared.
        // This handles methods on RuntimeProvided types and types not in the module.
        GenerateMissingMethodStubs(sb, emittedMethodDecls, userTypes, knownTypeNames);

        // Generate trivial method declarations for opaque Span/ReadOnlySpan stubs.
        // These types were discovered from BCL code locals/params but aren't full IRType objects.
        // The methods are trivial (get_Length returns f_length, get_IsEmpty returns f_length==0).
        _opaqueSpanStubs = opaqueSpanStubs;
        if (opaqueSpanStubs.Count > 0)
        {
            sb.AppendLine("// ===== Opaque Span Stub Methods =====");
            foreach (var spanType in opaqueSpanStubs)
            {
                var getLenSig = $"int32_t {spanType}_get_Length({spanType}* __this)";
                var isEmptySig = $"bool {spanType}_get_IsEmpty({spanType}* __this)";
                if (emittedMethodDecls.Add(getLenSig))
                    sb.AppendLine($"{getLenSig};");
                if (emittedMethodDecls.Add(isEmptySig))
                    sb.AppendLine($"{isEmptySig};");
            }
            sb.AppendLine();
        }

        // Generate SafeHandleMarshaller ManagedToUnmanagedIn method declarations.
        // These are trivial wrappers around SafeHandle ICalls (DangerousAddRef/GetHandle/Release).
        _opaqueSafeHandleMarshallerStubs = opaqueSafeHandleMarshallerStubs;
        if (opaqueSafeHandleMarshallerStubs.Count > 0)
        {
            sb.AppendLine("// ===== SafeHandleMarshaller Stub Methods =====");
            foreach (var shmType in opaqueSafeHandleMarshallerStubs)
            {
                var fromSig = $"void {shmType}_FromManaged({shmType}* __this, void* handle)";
                var toSig = $"intptr_t {shmType}_ToUnmanaged({shmType}* __this)";
                var freeSig = $"void {shmType}_Free({shmType}* __this)";
                if (emittedMethodDecls.Add(fromSig))
                    sb.AppendLine($"{fromSig};");
                if (emittedMethodDecls.Add(toSig))
                    sb.AppendLine($"{toSig};");
                if (emittedMethodDecls.Add(freeSig))
                    sb.AppendLine($"{freeSig};");
            }
            sb.AppendLine();
        }

        // Populate the declared function names and param counts for use by source generation.
        // This allows the source generator to filter out methods that call undeclared functions
        // or methods that call functions with wrong arg counts (overload mismatches).
        _declaredFunctionNames = ExtractFunctionNamesFromSignatures(emittedMethodDecls);
        _declaredFunctionParamCounts = ExtractFunctionParamCounts(emittedMethodDecls);

        // Static constructor guard declarations
        foreach (var type in userTypes)
        {
            if (type.HasCctor)
            {
                sb.AppendLine($"void {type.CppName}_ensure_cctor();");
            }
        }
        if (userTypes.Any(t => t.HasCctor))
            sb.AppendLine();

        // String literal initializer and extern declarations
        if (_module.StringLiterals.Count > 0)
        {
            sb.AppendLine("// String literal initializer");
            sb.AppendLine("void __init_string_literals();");
            sb.AppendLine();

            // Extern declarations for string literal variables (defined in data file)
            sb.AppendLine("// String literal extern declarations");
            foreach (var (_, literal) in _module.StringLiterals)
            {
                sb.AppendLine($"extern cil2cpp::String* {literal.Id};");
            }
            sb.AppendLine();
        }

        // Runtime TypeInfo VTable patching (must be called after __init_string_literals)
        sb.AppendLine("void __init_runtime_vtables();");
        sb.AppendLine();

        // Extern declarations for array initializer data (defined in data file)
        if (_module.ArrayInitDataBlobs.Count > 0)
        {
            sb.AppendLine("// Array initializer data extern declarations");
            foreach (var blob in _module.ArrayInitDataBlobs)
            {
                sb.AppendLine($"extern const unsigned char {blob.Id}[{blob.Data.Length}];");
            }
            sb.AppendLine();
        }

        return new GeneratedFile
        {
            FileName = $"{_module.Name}.h",
            Content = sb.ToString()
        };
    }

    private void GenerateStructDefinition(StringBuilder sb, IRType type, HashSet<string>? definedTypes = null)
    {
        sb.AppendLine($"// {type.ILFullName}");

        if (type.IsValueType)
        {
            sb.AppendLine($"struct {type.CppName} {{");
        }
        else
        {
            sb.AppendLine($"struct {type.CppName} {{");
            sb.AppendLine($"    cil2cpp::TypeInfo* __type_info;");
            sb.AppendLine($"    cil2cpp::UInt32 __sync_block;");

            // Base type fields (walk full inheritance chain)
            var inheritedFields = CollectInheritedFields(type);
            // Track inherited field names to avoid duplicate own fields (C2086)
            var inheritedFieldNames = new HashSet<string>();
            if (inheritedFields.Count > 0)
            {
                sb.AppendLine($"    // Inherited fields");
                // Detect C# field hiding (derived class `new` field shadows base field)
                // In .NET layout both fields coexist — disambiguate with ancestor suffix
                var emittedFieldNames = new HashSet<string>();
                // Track which ancestors we've already injected runtime-only fields for
                var injectedAncestors = new HashSet<string>();
                foreach (var (field, fromType) in inheritedFields)
                {
                    // Inject runtime-only C++ fields before the first BCL field of each
                    // RuntimeProvidedType ancestor (these fields exist in the runtime struct
                    // but not in IL metadata, and subtypes must include them for layout match)
                    if (injectedAncestors.Add(fromType.ILFullName) &&
                        RuntimeOnlyFields.TryGetValue(fromType.ILFullName, out var extraFields))
                    {
                        foreach (var (extraType, extraName) in extraFields)
                        {
                            sb.AppendLine($"    {extraType} {extraName}; // runtime-only from {fromType.ILFullName}");
                            inheritedFieldNames.Add(extraName);
                            emittedFieldNames.Add(extraName);
                        }
                    }
                    var cppType = SanitizeFieldType(field.FieldTypeName, definedTypes);
                    var fieldName = field.CppName;
                    if (!emittedFieldNames.Add(fieldName))
                    {
                        // Name collision — C# field hiding. Suffix with declaring type
                        var suffix = "_" + CppNameMapper.MangleTypeName(fromType.Name);
                        fieldName = field.CppName + suffix;
                    }
                    sb.AppendLine($"    {cppType} {fieldName}; // from {fromType.ILFullName}");
                    inheritedFieldNames.Add(field.CppName);
                }
            }

            // Own fields (skip fields already emitted as inherited)
            foreach (var field in type.Fields)
            {
                if (inheritedFieldNames.Contains(field.CppName)) continue;
                var cppType = SanitizeFieldType(field.FieldTypeName, definedTypes);
                sb.AppendLine($"    {cppType} {field.CppName};");
            }

            sb.AppendLine("};");
            sb.AppendLine();
            return;
        }

        if (type.ExplicitSize > 0)
        {
            // Types with explicit ClassSize metadata (ECMA-335 II.10.1.2).
            // Three sub-cases:
            //   1. FixedBuffer: single FixedElementField → emit as C array
            //   2. StaticArrayInitTypeSize: no fields → emit raw byte array
            //   3. Other: has fields + explicit size → emit fields + padding

            if (type.Fields.Count == 1 && type.Fields[0].Name == "FixedElementField")
            {
                // Case 1: Fixed-size buffer (C# fixed keyword / [InlineArray])
                var field = type.Fields[0];
                var cppType = SanitizeFieldType(field.FieldTypeName, definedTypes);
                int elemSize = GetPrimitiveSize(cppType);
                if (elemSize > 0)
                {
                    int count = type.ExplicitSize / elemSize;
                    sb.AppendLine($"    {cppType} {field.CppName}[{count}];");
                }
                else
                {
                    // Fallback: emit as raw byte array to guarantee correct sizeof
                    sb.AppendLine($"    uint8_t {field.CppName}[{type.ExplicitSize}]; // FIXME: unknown element type '{cppType}'");
                }
            }
            else if (type.Fields.Count == 0)
            {
                // Case 2: Opaque sized type (e.g., __StaticArrayInitTypeSize=N)
                sb.AppendLine($"    uint8_t __data[{type.ExplicitSize}];");
            }
            else
            {
                // Case 3: Regular struct with explicit size — emit fields + tail padding
                foreach (var field in type.Fields)
                {
                    var cppType = SanitizeFieldType(field.FieldTypeName, definedTypes);
                    sb.AppendLine($"    {cppType} {field.CppName};");
                }
            }
        }
        else
        {
            // Normal value type: emit fields as-is
            foreach (var field in type.Fields)
            {
                var cppType = SanitizeFieldType(field.FieldTypeName, definedTypes);
                sb.AppendLine($"    {cppType} {field.CppName};");
            }
        }

        sb.AppendLine("};");
        sb.AppendLine();
    }

    /// <summary>
    /// Try to forward-declare a type name if it's a pointer type to an unknown struct.
    /// </summary>
    private static void TryForwardDeclare(StringBuilder sb, string cppTypeName,
        HashSet<string> forwardDeclared, HashSet<string> aliasedTypes, HashSet<string> enumTypes)
    {
        var raw = cppTypeName.TrimEnd('*').Trim();
        if (raw.Length == 0 || raw.StartsWith("cil2cpp::") || IsCppPrimitiveType(raw)) return;
        if (aliasedTypes.Contains(raw)) return;
        if (!IsValidCppIdentifier(raw)) return;
        if (enumTypes.Contains(raw)) return;
        // Skip types with unresolved generic params (open generics that leaked through)
        if (MangledNameContainsUnresolvedGenericParam(raw)) return;
        if (!forwardDeclared.Contains(raw))
        {
            sb.AppendLine($"struct {raw};");
            forwardDeclared.Add(raw);
        }
    }

    /// <summary>
    /// Sanitize a field type for struct definition.
    /// If the type is a pointer to an unknown type, replace with void*.
    /// If the type is a value type not in the known set, it should have been stubbed.
    /// </summary>
    private static string SanitizeFieldType(string fieldTypeName, HashSet<string>? definedTypes)
    {
        var cppType = CppNameMapper.GetCppTypeForDecl(fieldTypeName);
        if (definedTypes == null) return cppType;

        // Check if the raw type name (without *) is known
        var rawType = cppType.TrimEnd('*').Trim();
        if (rawType.Length == 0 || rawType.StartsWith("cil2cpp::") || IsCppPrimitiveType(rawType))
            return cppType;

        if (!definedTypes.Contains(rawType))
        {
            // Unknown type — replace pointer fields with void*
            if (cppType.EndsWith("*"))
                return "void*";
            // Non-pointer unknown → should have been stubbed, but fallback to void*
            return "void*";
        }

        return cppType;
    }

    /// <summary>
    /// Collect unknown value types used as non-pointer fields in any struct.
    /// These need stub struct definitions to avoid C++ errors.
    /// </summary>
    private static void CollectUnknownValueTypeFields(
        List<IRType> types, HashSet<string> definedTypes, HashSet<string> stubs)
    {
        foreach (var type in types)
        {
            if (type.IsEnum || type.IsDelegate) continue;
            foreach (var field in type.Fields)
            {
                CheckFieldForStub(field.FieldTypeName, definedTypes, stubs);
            }
            // Also check inherited fields for reference types
            if (!type.IsValueType)
            {
                var inherited = CollectInheritedFields(type);
                foreach (var (field, _) in inherited)
                    CheckFieldForStub(field.FieldTypeName, definedTypes, stubs);
            }
            // Check static fields
            foreach (var field in type.StaticFields)
                CheckFieldForStub(field.FieldTypeName, definedTypes, stubs);
        }
    }

    /// <summary>
    /// Scan method locals, parameters, and return types for unknown non-pointer value types
    /// and add opaque stubs. This catches value types like Span&lt;T&gt;, EventData, ListBuilder&lt;T&gt;,
    /// ReadOnlySpan&lt;T&gt; etc. that don't have struct definitions in the IR module.
    /// </summary>
    private static void CollectUnknownValueTypeLocals(
        List<IRType> types, HashSet<string> definedTypes, HashSet<string> stubs)
    {
        foreach (var type in types)
        {
            if (type.IsEnum || type.IsDelegate) continue;
            foreach (var method in type.Methods)
            {
                // Scan locals
                foreach (var local in method.Locals)
                    TryAddValueTypeStub(local.CppTypeName, definedTypes, stubs);

                // Scan parameters (non-pointer value types in method signatures)
                foreach (var param in method.Parameters)
                    TryAddValueTypeStub(param.CppTypeName, definedTypes, stubs);

                // Scan return type
                if (!string.IsNullOrEmpty(method.ReturnTypeCpp))
                    TryAddValueTypeStub(method.ReturnTypeCpp, definedTypes, stubs);
            }
        }
    }

    private static void TryAddValueTypeStub(string cppType, HashSet<string> definedTypes, HashSet<string> stubs)
    {
        if (string.IsNullOrEmpty(cppType)) return;
        if (cppType.EndsWith("*")) return; // pointer types only need forward decl
        var rawType = cppType.Trim();
        if (rawType.Length == 0 || rawType.StartsWith("cil2cpp::") ||
            IsCppPrimitiveType(rawType)) return;
        if (definedTypes.Contains(rawType)) return;
        if (!IsValidCppIdentifier(rawType)) return;
        // Skip unresolved generic params (TChar, T1, etc.) — no underscore
        if (!rawType.Contains('_')) return;
        stubs.Add(rawType);
    }

    /// <summary>
    /// Scan method body IRRawCpp instructions for sizeof(TypeName) patterns and add those types
    /// as opaque stubs. This catches cases where a type is used only inside sizeof() but not as
    /// a local variable (e.g., EventSource.EventData used in WriteEvent patterns).
    /// </summary>
    private static void CollectUnknownValueTypesFromSizeof(
        List<IRType> types, HashSet<string> definedTypes, HashSet<string> stubs)
    {
        foreach (var type in types)
        {
            if (type.IsEnum || type.IsDelegate) continue;
            foreach (var method in type.Methods)
            {
                foreach (var block in method.BasicBlocks)
                {
                    foreach (var instr in block.Instructions)
                    {
                        if (instr is not IR.IRRawCpp rawCpp) continue;
                        var code = rawCpp.Code;
                        int idx = 0;
                        while ((idx = code.IndexOf("sizeof(", idx)) >= 0)
                        {
                            var start = idx + 7;
                            var end = code.IndexOf(')', start);
                            if (end > start)
                            {
                                var typeName = code[start..end].Trim();
                                TryAddValueTypeStub(typeName, definedTypes, stubs);
                            }
                            idx = start;
                        }
                    }
                }
            }
        }
    }

    private static void CheckFieldForStub(string fieldTypeName, HashSet<string> definedTypes, HashSet<string> stubs)
    {
        var cppType = CppNameMapper.GetCppTypeForDecl(fieldTypeName);
        if (cppType.EndsWith("*")) return; // Pointers will be replaced with void*
        var rawType = cppType.Trim();
        if (rawType.Length == 0 || rawType.StartsWith("cil2cpp::") || IsCppPrimitiveType(rawType)) return;
        if (definedTypes.Contains(rawType)) return;
        if (!IsValidCppIdentifier(rawType)) return;
        stubs.Add(rawType);
    }

    /// <summary>
    /// Topologically sort struct types by value-type field dependencies.
    /// If struct A has a non-pointer field of type B, B must come before A.
    /// </summary>
    private static List<IRType> TopologicalSortByFieldDeps(List<IRType> types, HashSet<string> aliasedTypes)
    {
        var typeMap = new Dictionary<string, IRType>();
        foreach (var t in types)
            typeMap[t.CppName] = t;

        var visited = new HashSet<string>();
        var inStack = new HashSet<string>();
        var result = new List<IRType>();

        foreach (var t in types)
        {
            if (!visited.Contains(t.CppName))
                TopoVisit(t, typeMap, aliasedTypes, visited, inStack, result);
        }

        return result;
    }

    private static void TopoVisit(IRType type, Dictionary<string, IRType> typeMap,
        HashSet<string> aliasedTypes, HashSet<string> visited, HashSet<string> inStack,
        List<IRType> result)
    {
        if (visited.Contains(type.CppName)) return;
        if (inStack.Contains(type.CppName)) return; // Cycle — break it

        inStack.Add(type.CppName);

        // Collect all field types (own + inherited)
        var allFields = new List<string>();
        foreach (var f in type.Fields)
            allFields.Add(f.FieldTypeName);
        if (!type.IsValueType)
        {
            var inherited = CollectInheritedFields(type);
            foreach (var (f, _) in inherited)
                allFields.Add(f.FieldTypeName);
        }
        foreach (var f in type.StaticFields)
            allFields.Add(f.FieldTypeName);

        foreach (var fieldTypeName in allFields)
        {
            var cppType = CppNameMapper.GetCppTypeForDecl(fieldTypeName);
            if (cppType.EndsWith("*")) continue; // Pointers don't need ordering
            var rawType = cppType.Trim();
            if (rawType.StartsWith("cil2cpp::") || IsCppPrimitiveType(rawType)) continue;
            if (aliasedTypes.Contains(rawType)) continue;
            if (typeMap.TryGetValue(rawType, out var dep))
                TopoVisit(dep, typeMap, aliasedTypes, visited, inStack, result);
        }

        inStack.Remove(type.CppName);
        visited.Add(type.CppName);
        result.Add(type);
    }

    private static List<(IRField Field, IRType FromType)> CollectInheritedFields(IRType type)
    {
        var result = new List<(IRField, IRType)>();
        var ancestors = new List<IRType>();
        var current = type.BaseType;
        while (current != null && current.ILFullName != "System.Object")
        {
            ancestors.Add(current);
            current = current.BaseType;
        }
        ancestors.Reverse(); // furthest ancestor first
        foreach (var ancestor in ancestors)
        {
            foreach (var field in ancestor.Fields)
                result.Add((field, ancestor));
        }
        return result;
    }

    /// <summary>
    /// Runtime-only C++ fields for RuntimeProvidedTypes whose runtime struct
    /// has additional fields not present in the IL metadata.
    /// These must be injected into subtypes so their memory layout matches
    /// the runtime struct (e.g. cil2cpp::Task has 4 extra fields before BCL fields).
    /// Key: IL full name of the RuntimeProvidedType ancestor.
    /// Value: ordered list of (C++ type, field name) pairs.
    /// </summary>
    private static readonly Dictionary<string, (string CppType, string CppName)[]> RuntimeOnlyFields = new()
    {
        ["System.Threading.Tasks.Task"] = new[]
        {
            ("int32_t", "f_status"),
            ("cil2cpp::Exception*", "f_exception"),
            ("void*", "f_continuations"),
            ("void*", "f_lock"),
        },
    };

    /// <summary>

    // REMOVED: HasUnknownParameterTypes, HasUnknownBodyReferences,
    // HasUnknownInstructionReference, IsUnknownValueType, IsUnknownTypeReference,
    // HasUnresolvedGenericParamInCode, IsCallToUnknownType
    // These were pre-render gates that masked tree-shaking issues.

    private static bool IsCppPrimitiveType(string typeName)
    {
        return typeName is "bool" or "int8_t" or "uint8_t" or "int16_t" or "uint16_t"
            or "int32_t" or "uint32_t" or "int64_t" or "uint64_t" or "float" or "double"
            or "char16_t" or "intptr_t" or "uintptr_t" or "void";
    }

    /// <summary>
    /// Get the size in bytes of a C++ primitive type name.
    /// Returns 0 for unknown / non-primitive types.
    /// </summary>
    private static int GetPrimitiveSize(string cppType)
    {
        return cppType switch
        {
            "bool" or "int8_t" or "uint8_t" => 1,
            "int16_t" or "uint16_t" or "char16_t" => 2,
            "int32_t" or "uint32_t" or "float" => 4,
            "int64_t" or "uint64_t" or "double" => 8,
            "intptr_t" or "uintptr_t" => 8, // 64-bit assumption
            _ => 0,
        };
    }

    /// <summary>
    /// Get using aliases for runtime-provided types (mangled name → cil2cpp:: struct).
    /// </summary>
    private static IEnumerable<(string Mangled, string CppAlias)> GetRuntimeProvidedTypeAliases()
    {
        // Core runtime types
        yield return ("System_Object", "cil2cpp::Object");
        yield return ("System_String", "cil2cpp::String");
        yield return ("System_Array", "cil2cpp::Array");
        yield return ("System_Delegate", "cil2cpp::Delegate");
        yield return ("System_MulticastDelegate", "cil2cpp::Delegate");
        yield return ("System_Type", "cil2cpp::Object");  // Type represented as opaque pointer
        yield return ("System_RuntimeType", "cil2cpp::Type");  // Phase I.2: RuntimeType = Type (Unity IL2CPP pattern)
        yield return ("System_Attribute", "cil2cpp::Object");  // Base class for all attributes
        yield return ("System_Enum", "cil2cpp::Object");  // Abstract base for enums — same layout as Object
        yield return ("System_ValueType", "cil2cpp::Object");  // Abstract base for value types — same layout as Object

        // Exception hierarchy — all map to runtime C++ exception types
        yield return ("System_Exception", "cil2cpp::Exception");
        yield return ("System_NullReferenceException", "cil2cpp::NullReferenceException");
        yield return ("System_IndexOutOfRangeException", "cil2cpp::IndexOutOfRangeException");
        yield return ("System_InvalidCastException", "cil2cpp::InvalidCastException");
        yield return ("System_InvalidOperationException", "cil2cpp::InvalidOperationException");
        yield return ("System_ObjectDisposedException", "cil2cpp::ObjectDisposedException");
        yield return ("System_NotSupportedException", "cil2cpp::NotSupportedException");
        yield return ("System_PlatformNotSupportedException", "cil2cpp::PlatformNotSupportedException");
        yield return ("System_NotImplementedException", "cil2cpp::NotImplementedException");
        yield return ("System_ArgumentException", "cil2cpp::ArgumentException");
        yield return ("System_ArgumentNullException", "cil2cpp::ArgumentNullException");
        yield return ("System_ArgumentOutOfRangeException", "cil2cpp::ArgumentOutOfRangeException");
        yield return ("System_ArithmeticException", "cil2cpp::ArithmeticException");
        yield return ("System_OverflowException", "cil2cpp::OverflowException");
        yield return ("System_DivideByZeroException", "cil2cpp::DivideByZeroException");
        yield return ("System_FormatException", "cil2cpp::FormatException");
        yield return ("System_RankException", "cil2cpp::RankException");
        yield return ("System_ArrayTypeMismatchException", "cil2cpp::ArrayTypeMismatchException");
        yield return ("System_TypeInitializationException", "cil2cpp::TypeInitializationException");
        yield return ("System_TimeoutException", "cil2cpp::TimeoutException");
        yield return ("System_AggregateException", "cil2cpp::AggregateException");
        yield return ("System_OperationCanceledException", "cil2cpp::OperationCanceledException");
        yield return ("System_Threading_Tasks_TaskCanceledException", "cil2cpp::TaskCanceledException");
        yield return ("System_Collections_Generic_KeyNotFoundException", "cil2cpp::KeyNotFoundException");

        // Phase II.3: Runtime reflection subtypes → existing runtime structs
        yield return ("System_Reflection_RuntimeMethodInfo", "cil2cpp::ManagedMethodInfo");
        yield return ("System_Reflection_RuntimeFieldInfo", "cil2cpp::ManagedFieldInfo");
        yield return ("System_Reflection_RuntimeConstructorInfo", "cil2cpp::ManagedMethodInfo");
        yield return ("System_Reflection_TypeInfo", "cil2cpp::Type");
        // Phase II.4: New runtime structs for Assembly + PropertyInfo
        yield return ("System_Reflection_RuntimePropertyInfo", "cil2cpp::ManagedPropertyInfo");
        yield return ("System_Reflection_Assembly", "cil2cpp::ManagedAssembly");
        yield return ("System_Reflection_RuntimeAssembly", "cil2cpp::ManagedAssembly");
        // Phase II.5: WaitHandle hierarchy
        yield return ("System_Threading_WaitHandle", "cil2cpp::ManagedWaitHandle");
        yield return ("System_Threading_EventWaitHandle", "cil2cpp::ManagedEventWaitHandle");
        yield return ("System_Threading_ManualResetEvent", "cil2cpp::ManagedEventWaitHandle");
        yield return ("System_Threading_AutoResetEvent", "cil2cpp::ManagedEventWaitHandle");
        yield return ("System_Threading_Mutex", "cil2cpp::ManagedMutex");
        yield return ("System_Threading_Semaphore", "cil2cpp::ManagedSemaphore");
    }

    /// <summary>
    /// Get using aliases for primitive types (mangled name → C++ built-in type).
    /// Primitive types map directly to C++ built-in types; no struct is emitted.
    /// </summary>
    private static IEnumerable<(string Mangled, string CppAlias)> GetPrimitiveTypeAliases()
    {
        yield return ("System_Boolean", "bool");
        yield return ("System_Byte", "uint8_t");
        yield return ("System_SByte", "int8_t");
        yield return ("System_Int16", "int16_t");
        yield return ("System_UInt16", "uint16_t");
        yield return ("System_Int32", "int32_t");
        yield return ("System_UInt32", "uint32_t");
        yield return ("System_Int64", "int64_t");
        yield return ("System_UInt64", "uint64_t");
        yield return ("System_Single", "float");
        yield return ("System_Double", "double");
        yield return ("System_Char", "char16_t");
        yield return ("System_IntPtr", "intptr_t");
        yield return ("System_UIntPtr", "uintptr_t");
    }

    /// <summary>
    /// Types whose "using System_X = cil2cpp::Y;" alias is already defined in runtime headers
    /// (task.h, memberinfo.h, cancellation.h, async_enumerable.h).
    /// The codegen must NOT emit struct definitions OR using aliases for these —
    /// the runtime headers handle both.
    /// </summary>
    private static readonly HashSet<string> RuntimeHeaderAliasedTypes = new()
    {
        // task.h
        "System_Threading_Tasks_Task",
        "System_Runtime_CompilerServices_TaskAwaiter",
        "System_Runtime_CompilerServices_AsyncTaskMethodBuilder",
        // IAsyncStateMachine: removed from runtime (Phase IV.1) — now compiled from BCL IL
        // memberinfo.h
        "System_Reflection_MemberInfo",
        "System_Reflection_MethodBase",
        "System_Reflection_MethodInfo",
        "System_Reflection_FieldInfo",
        "System_Reflection_ParameterInfo",
        // cancellation.h
        "System_Threading_CancellationTokenSource",
        "System_Threading_CancellationToken",
        // async_enumerable.h
        "System_Threading_Tasks_ValueTask",
        "System_Runtime_CompilerServices_ValueTaskAwaiter",
        "System_Runtime_CompilerServices_AsyncIteratorMethodBuilder",
        // threading.h — ManagedThread is in cil2cpp namespace but no using alias;
        // still needs to be skipped since runtime defines the struct
        "System_Threading_Thread",
        // typed_reference.h
        "System_TypedReference",
        "System_ArgIterator",
        // Phase II.3: Runtime reflection subtypes — aliases in memberinfo.h / reflection.h
        "System_Reflection_RuntimeMethodInfo",
        "System_Reflection_RuntimeFieldInfo",
        "System_Reflection_RuntimeConstructorInfo",
        "System_Reflection_TypeInfo",
        // Phase II.4: Assembly + PropertyInfo — aliases in assembly.h
        "System_Reflection_RuntimePropertyInfo",
        "System_Reflection_Assembly",
        "System_Reflection_RuntimeAssembly",
        // Phase II.5: WaitHandle hierarchy — aliases in waithandle.h
        "System_Threading_WaitHandle",
        "System_Threading_EventWaitHandle",
        "System_Threading_ManualResetEvent",
        "System_Threading_AutoResetEvent",
        "System_Threading_Mutex",
        "System_Threading_Semaphore",
    };

    /// <summary>
    /// Get TypeInfo reference aliases for runtime exception types.
    /// Maps mangled IL names (System_Exception) to runtime-declared TypeInfo names (cil2cpp::Exception_TypeInfo).
    /// Used by castclass/isinst/catch to reference exception TypeInfos by their mangled names.
    /// </summary>
    private static IEnumerable<(string MangledName, string RuntimeTypeInfoName)> GetExceptionTypeInfoAliases()
    {
        yield return ("System_Exception", "cil2cpp::Exception_TypeInfo");
        yield return ("System_NullReferenceException", "cil2cpp::NullReferenceException_TypeInfo");
        yield return ("System_IndexOutOfRangeException", "cil2cpp::IndexOutOfRangeException_TypeInfo");
        yield return ("System_InvalidCastException", "cil2cpp::InvalidCastException_TypeInfo");
        yield return ("System_InvalidOperationException", "cil2cpp::InvalidOperationException_TypeInfo");
        yield return ("System_ObjectDisposedException", "cil2cpp::ObjectDisposedException_TypeInfo");
        yield return ("System_NotSupportedException", "cil2cpp::NotSupportedException_TypeInfo");
        yield return ("System_PlatformNotSupportedException", "cil2cpp::PlatformNotSupportedException_TypeInfo");
        yield return ("System_NotImplementedException", "cil2cpp::NotImplementedException_TypeInfo");
        yield return ("System_ArgumentException", "cil2cpp::ArgumentException_TypeInfo");
        yield return ("System_ArgumentNullException", "cil2cpp::ArgumentNullException_TypeInfo");
        yield return ("System_ArgumentOutOfRangeException", "cil2cpp::ArgumentOutOfRangeException_TypeInfo");
        yield return ("System_ArithmeticException", "cil2cpp::ArithmeticException_TypeInfo");
        yield return ("System_OverflowException", "cil2cpp::OverflowException_TypeInfo");
        yield return ("System_DivideByZeroException", "cil2cpp::DivideByZeroException_TypeInfo");
        yield return ("System_FormatException", "cil2cpp::FormatException_TypeInfo");
        yield return ("System_RankException", "cil2cpp::RankException_TypeInfo");
        yield return ("System_ArrayTypeMismatchException", "cil2cpp::ArrayTypeMismatchException_TypeInfo");
        yield return ("System_TypeInitializationException", "cil2cpp::TypeInitializationException_TypeInfo");
        yield return ("System_TimeoutException", "cil2cpp::TimeoutException_TypeInfo");
        yield return ("System_AggregateException", "cil2cpp::AggregateException_TypeInfo");
        yield return ("System_OperationCanceledException", "cil2cpp::OperationCanceledException_TypeInfo");
        yield return ("System_Threading_Tasks_TaskCanceledException", "cil2cpp::TaskCanceledException_TypeInfo");
        yield return ("System_Collections_Generic_KeyNotFoundException", "cil2cpp::KeyNotFoundException_TypeInfo");
    }

    /// <summary>
    /// Runtime-provided base types that need stub TypeInfo definitions in generated code.
    /// These are referenced as .base_type for value types, enums, and delegates.
    /// </summary>
    private static IEnumerable<(string MangledName, string ILFullName)> GetRuntimeBaseTypeInfoStubs()
    {
        yield return ("System_ValueType", "System.ValueType");
        yield return ("System_Enum", "System.Enum");
        yield return ("System_MulticastDelegate", "System.MulticastDelegate");
        yield return ("System_Delegate", "System.Delegate");
    }

    /// <summary>
    /// Scan all method bodies for function calls, and generate stub declarations
    /// for any called function that wasn't declared. This handles methods on
    /// RuntimeProvided types and types not in the IR module.
    /// </summary>
    private void GenerateMissingMethodStubs(StringBuilder sb, HashSet<string> emittedMethodDecls,
        List<IR.IRType> userTypes, HashSet<string> knownTypeNames)
    {
        // Build lookup: method CppName → IRMethod (for finding signatures)
        var methodLookup = new Dictionary<string, IR.IRMethod>();
        foreach (var type in _module.Types)
        {
            foreach (var method in type.Methods)
            {
                methodLookup.TryAdd(method.CppName, method);
            }
        }

        // Build declared function names from already-emitted declarations.
        // Used both for UF prediction (callee scan) and for finding missing functions.
        var declaredNames = new HashSet<string>();
        foreach (var sig in emittedMethodDecls)
        {
            var parenIdx = sig.IndexOf('(');
            if (parenIdx > 0)
            {
                var beforeParen = sig[..parenIdx].TrimEnd();
                var spaceIdx = beforeParen.LastIndexOf(' ');
                if (spaceIdx >= 0)
                    declaredNames.Add(beforeParen[(spaceIdx + 1)..]);
                var starIdx = beforeParen.LastIndexOf('*');
                if (starIdx > spaceIdx)
                    declaredNames.Add(beforeParen[(starIdx + 1)..].TrimStart());
            }
        }

        // Collect all called function names from method bodies that WILL be compiled.
        // Scan userTypes (excludes unresolved generic params) but include RuntimeProvided
        // — their method bodies may call ctors on other CoreRuntimeTypes that need declarations.
        // Apply the same filters as EmitMethodsForType in Source.cs to exclude methods that
        // won't actually be emitted (invalid signatures, generic conflicts, etc.).
        var calledFunctions = new HashSet<string>();
        foreach (var type in userTypes)
        {
            if (type.IsDelegate) continue;
            bool isSkippedType0 = IRBuilder.SkipAllMethodsTypes.Contains(type.ILFullName);
            foreach (var method in type.Methods)
            {
                if (method.IsAbstract || method.IsInternalCall) continue;
                if (method.BasicBlocks.Count == 0 && !method.IsPInvoke) continue;
                if (method.IrStubReason != null) continue;
                if (method.HasICallMapping) continue;
                if (isSkippedType0) continue;
                if (!method.IsStatic && IRBuilder.CoreRuntimeTypes.Contains(type.ILFullName)) continue;
                if (HasInvalidCppSignature(method)) continue;
                if (HasGenericBodyTypeConflict(type, method)) continue;

                foreach (var block in method.BasicBlocks)
                {
                    foreach (var instr in block.Instructions)
                    {
                        if (instr is IR.IRCall call && !string.IsNullOrEmpty(call.FunctionName)
                            && !call.FunctionName.StartsWith("cil2cpp::"))
                        {
                            calledFunctions.Add(call.FunctionName);
                        }
                        else if (instr is IR.IRNewObj newObj && !string.IsNullOrEmpty(newObj.CtorName)
                            && !newObj.CtorName.StartsWith("cil2cpp::"))
                        {
                            calledFunctions.Add(newObj.CtorName);
                        }
                        else if (instr is IR.IRLoadFunctionPointer ldftn && !string.IsNullOrEmpty(ldftn.MethodCppName)
                            && !ldftn.MethodCppName.StartsWith("cil2cpp::") && !ldftn.IsVirtual)
                        {
                            calledFunctions.Add(ldftn.MethodCppName);
                        }
                    }
                }
            }
        }

        // Build the undeclared function set from the initial scan.
        {
            var initialMissing = new List<(string name, IR.IRMethod? method)>();
            foreach (var funcName in calledFunctions)
            {
                if (declaredNames.Contains(funcName)) continue;
                methodLookup.TryGetValue(funcName, out var irMethod);
                initialMissing.Add((funcName, irMethod));
            }
            foreach (var (funcName, irMethod) in initialMissing)
            {
                if (irMethod == null || HasInvalidCppSignature(irMethod))
                    _undeclaredFunctionNames.Add(funcName);
            }
        }

        // Final: build missing functions list from remaining calledFunctions
        var missingFunctions = new List<(string name, IR.IRMethod? method)>();
        foreach (var funcName in calledFunctions)
        {
            if (declaredNames.Contains(funcName)) continue;
            methodLookup.TryGetValue(funcName, out var irMethod);
            missingFunctions.Add((funcName, irMethod));
        }

        if (missingFunctions.Count == 0) return;

        // Separate CoreRuntimeTypes methods (extern "C" linkage — defined in runtime library)
        // from other missing methods (normal C++ linkage — defined in generated code)
        var coreRuntimeDecls = new List<string>();
        var normalDecls = new List<string>();

        sb.AppendLine("// ===== Missing Method Declarations (RuntimeProvided or cross-reference) =====");
        foreach (var (funcName, irMethod) in missingFunctions.OrderBy(m => m.name))
        {
            if (irMethod != null && !HasInvalidCppSignature(irMethod))
            {
                var sig = irMethod.GetCppSignature();
                if (emittedMethodDecls.Add(sig))
                {
                    // CoreRuntimeTypes methods use extern "C" — their implementations
                    // are in the runtime library (core_methods.cpp), not generated code.
                    var typeName = irMethod.DeclaringType?.ILFullName ?? "";
                    if (IRBuilder.CoreRuntimeTypes.Contains(typeName)
                        || IRBuilder.SkipAllMethodsTypes.Contains(typeName)
                        || IRBuilder.ClrInternalTypeNames.Contains(typeName))
                    {
                        coreRuntimeDecls.Add(sig);
                    }
                    else
                    {
                        normalDecls.Add(sig);
                    }
                    declaredNames.Add(funcName);
                }
            }
            else
            {
                // Track undeclared functions — methods calling these will be skipped in source emission
                _undeclaredFunctionNames.Add(funcName);
                var reason = irMethod == null ? "NOT_IN_MODULE" : "INVALID_SIGNATURE";
                sb.AppendLine($"// MISSING: {funcName} ({reason})");
            }
        }

        // Emit normal declarations (C++ linkage)
        foreach (var sig in normalDecls)
            sb.AppendLine($"{sig};");

        // Emit CoreRuntimeTypes declarations with extern "C" linkage.
        // The runtime library (core_methods.cpp) provides matching extern "C" definitions.
        if (coreRuntimeDecls.Count > 0)
        {
            sb.AppendLine("extern \"C\" {");
            foreach (var sig in coreRuntimeDecls)
                sb.AppendLine($"  {sig};");
            sb.AppendLine("}");
        }
        sb.AppendLine();
    }

    private void GenerateEnumDefinition(StringBuilder sb, IRType type)
    {
        var underlyingCppType = CppNameMapper.GetCppTypeForDecl(type.EnumUnderlyingType ?? "System.Int32");
        sb.AppendLine($"// {type.ILFullName} (enum)");
        sb.AppendLine($"using {type.CppName} = {underlyingCppType};");

        // Emit named constants
        foreach (var field in type.StaticFields)
        {
            if (field.ConstantValue != null)
            {
                sb.AppendLine($"constexpr {underlyingCppType} {type.CppName}_{field.CppName} = {field.ConstantValue};");
            }
        }
        sb.AppendLine();
    }

    /// <summary>
    /// Extract function names from C++ method signatures.
    /// Signature format: "retType funcName(params)" → extract "funcName".
    /// </summary>
    private static HashSet<string> ExtractFunctionNamesFromSignatures(HashSet<string> signatures)
    {
        var names = new HashSet<string>();
        foreach (var sig in signatures)
        {
            var parenIdx = sig.IndexOf('(');
            if (parenIdx <= 0) continue;

            var beforeParen = sig[..parenIdx].TrimEnd();
            var spaceIdx = beforeParen.LastIndexOf(' ');
            if (spaceIdx >= 0)
            {
                var name = beforeParen[(spaceIdx + 1)..];
                // Handle pointer return types: "retType* funcName"
                if (name.StartsWith("*"))
                    name = name.TrimStart('*');
                if (!string.IsNullOrEmpty(name))
                    names.Add(name);
            }
        }
        return names;
    }

    /// <summary>

    // REMOVED: CallsUndeclaredOrMismatchedFunctions, HasKnownBrokenPatterns,
    // InstructionHasBrokenPattern, HasUndeclaredTypeInfoRef, CollectBodyPointerTypeRefs
    // These were pre/post-render gates that masked tree-shaking and IR issues.

    /// Collect all type names referenced as _TypeInfo in a C++ code string.
    /// Used to auto-generate TypeInfo declarations for types referenced in method bodies.
    /// </summary>
    private static void CollectTypeInfoRefs(string code, HashSet<string> result)
    {
        var tiIdx = 0;
        while ((tiIdx = code.IndexOf("_TypeInfo", tiIdx)) >= 0)
        {
            int start = tiIdx - 1;
            while (start >= 0 && (char.IsLetterOrDigit(code[start]) || code[start] == '_'))
                start--;
            start++;
            if (start < tiIdx)
            {
                var typeName = code[start..tiIdx];
                // Skip cil2cpp:: prefixed refs (runtime-defined)
                if (start >= 2 && code[(start - 2)..start] == "::")
                {
                    tiIdx += 9;
                    continue;
                }
                if (!string.IsNullOrEmpty(typeName) && !typeName.StartsWith("cil2cpp"))
                {
                    // Handle types whose name ENDS with "TypeInfo" (e.g., System.Reflection.TypeInfo).
                    // The reference is System_Reflection_TypeInfo_TypeInfo — the first _TypeInfo is
                    // part of the type name. Check the char after "_TypeInfo" — if it's also "_TypeInfo",
                    // then the real type name includes the first "_TypeInfo".
                    var afterTi = tiIdx + 9; // position after first "_TypeInfo"
                    if (afterTi + 9 <= code.Length && code.Substring(afterTi, 9) == "_TypeInfo")
                    {
                        // The real type name is typeName + "_TypeInfo"
                        result.Add(typeName + "_TypeInfo");
                        tiIdx = afterTi + 9;
                        continue;
                    }
                    result.Add(typeName);
                }
            }
            tiIdx += 9;
        }
    }

    /// <summary>


    /// <summary>
    /// Extract function name → set of valid parameter counts from C++ signatures.
    /// Signature format: "retType funcName(Type1 p1, Type2 p2, ...)" → funcName → {2}
    /// </summary>
    private static Dictionary<string, HashSet<int>> ExtractFunctionParamCounts(HashSet<string> signatures)
    {
        var result = new Dictionary<string, HashSet<int>>();
        foreach (var sig in signatures)
        {
            var parenIdx = sig.IndexOf('(');
            if (parenIdx <= 0) continue;

            // Extract function name
            var beforeParen = sig[..parenIdx].TrimEnd();
            var spaceIdx = beforeParen.LastIndexOf(' ');
            if (spaceIdx < 0) continue;
            var name = beforeParen[(spaceIdx + 1)..];
            if (name.StartsWith("*"))
                name = name.TrimStart('*');
            if (string.IsNullOrEmpty(name)) continue;

            // Count parameters (count commas + 1, handle void/empty)
            var closeIdx = sig.IndexOf(')', parenIdx);
            if (closeIdx < 0) continue;
            var paramStr = sig[(parenIdx + 1)..closeIdx].Trim();
            int paramCount = 0;
            if (!string.IsNullOrEmpty(paramStr) && paramStr != "void")
            {
                paramCount = 1;
                // Count commas not inside nested angle brackets or parens
                int depth = 0;
                foreach (var ch in paramStr)
                {
                    if (ch is '<' or '(') depth++;
                    else if (ch is '>' or ')') depth--;
                    else if (ch == ',' && depth == 0) paramCount++;
                }
            }

            if (!result.TryGetValue(name, out var counts))
            {
                counts = new HashSet<int>();
                result[name] = counts;
            }
            counts.Add(paramCount);
        }
        return result;
    }

    /// <summary>
    /// Scan rendered C++ code for type names used as pointer types (e.g., "TypeName*")
    /// so they can be forward-declared in the header. This is needed for correct C++ compilation.
    /// </summary>
    private static void CollectBodyPointerTypeRefs(string code, HashSet<string> result)
    {
        int i = 0;
        while (i < code.Length)
        {
            int starIdx = code.IndexOf('*', i);
            if (starIdx < 0) break;

            // Walk backwards past any extra '*' (double pointers)
            int end = starIdx;
            while (end > 0 && code[end - 1] == '*') end--;
            // Walk backwards to find the start of the identifier
            int start = end - 1;
            while (start >= 0 && (char.IsLetterOrDigit(code[start]) || code[start] == '_'))
                start--;
            start++;

            if (start < end)
            {
                var typeName = code[start..end];
                // Only consider mangled .NET type names (contain underscore, start with uppercase)
                if (typeName.Length > 3 && typeName.Contains('_') && char.IsUpper(typeName[0]))
                {
                    // Skip if preceded by "::" (cil2cpp:: namespace)
                    if (start >= 2 && code[(start - 2)..start] == "::")
                    {
                        i = starIdx + 1;
                        continue;
                    }
                    result.Add(typeName);
                }
            }

            i = starIdx + 1;
        }
    }
}
